#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation
app:
    resource: "@AppBundle/Controller/"
    type: rest
    prefix: /api

api_login_check:
    path: /api/login_check

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
users:
    type: rest
    resource: AppBundle\Controller\UsersController